### PR TITLE
Fix: no pdfunite when downloading single file documents

### LINKED ISSUE #6: Problem with pdfunite
Hey guys,

I can now upload and view documents, but when I try to download them, I'm getting this stacktrace:

```
clojure.lang.ExceptionInfo: pdfunit didn't terminate correctly {:exit-code 99, :args ("/tmp/pdfseparate-2586469553236351662.pdf" "/tmp/pdfunite-123464094108447981.pdf"), :pages (#object[java.io.File 0x61dc0674 "/tmp/pdfseparate-2586469553236351662.pdf"])}
    at clojure.core$ex_info.invoke(core.clj:4591)
    at pepa.pdf$merge_pages.invoke(pdf.clj:177)
    at pepa.model$document_pdf.invoke(model.clj:480)
    at pepa.web.handlers$document_download$fn__15620$fn__15623.invoke(handlers.clj:219)
    at liberator.core$decide.invoke(core.clj:80)
[...]
```

This is what I see in the repl:

```
21:13:37.990 INFO  [Database] Generating PDF for 5
pdfunite version 0.24.5
Copyright 2005-2013 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
Usage: pdfunite [options] <PDF-sourcefile-1>..<PDF-sourcefile-n> <PDF-destfile>
  -v             : print copyright and version info
  -h             : print usage information
  -help          : print usage information
  --help         : print usage information
  -?             : print usage information
```

Feels like the process is not correctly invoked. I hope the pdfunite version I have is recent enough?

And why is it actually merging pdfs? I thought the file I uploaded would be stored as it is, and then downloaded as it is?

### PR DESCRIPTION
**Pull request by BernhardBln**
This fixes #6 for me. Wasn't able to try this with multi-page-file pdfs, as I didn't understand how to get those into the system.

### CODE REVIEW

**Comment by the-kenny** [comment]
This isn't exactly how it works.

The issue isn't the page count of the documents, but the count of files
they consist of.

Pepa makes a distinction between logical documents and files. A document
can consist of pages from many different files. A file maps to a pdf file
you uploaded.

Now most documents just have one file, that's the simple case that
shouldn't need pdfunite. The more complex case is when a document consists
of multiple files. Then we have to splice these files to extract the pages
we want and merge them to a new PDF file.

The former case was optimized for some time but isn't anymore. I'll
re-implement that as soon as I can.

**Comment by BernhardBln** [comment]
Alright, I'll wait for your patch then. Found a couple of other issues, should I open them here, or are you doing some general regression testing at the moment anyway?

**Comment by BernhardBln** [comment]
PS wouldn't mind helping, but I guess I have to understand the internal data structures a little better before.

**Comment by the-kenny** [comment]
Don't worry :) We're glad you found this. I'll keep you updated!

**Pull request closed without merging**
